version: '3.9'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    networks:
      - nextcloud
    volumes:
      - app_data:/var/www/html
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 2380:80      #此处：左侧的端口是nextcloud暴漏公网的地址
      - 4433:443
    networks:
      - nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf     #这是nginx的配置文件可以自定义修改
      - app_data:/var/www/html
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql123          #这是mariadb的root密码
      - MYSQL_PASSWORD=Msql123                #这是ariadb的用户密码
      - MYSQL_DATABASE=nextcloud              #数据库名可自定义
      - MYSQL_USER=nextcloud                  #数据库用户名
    networks:
      - nextcloud
  onlyoffice:
    image: onlyoffice/documentserver
    environment:
      - JWT_SECRET=asdqwezxc123    #这是onlyoffice的秘钥
    volumes:
       - './onlyoffice/DocumentServer/db:/var/lib/postgresql'
       - './onlyoffice/DocumentServer/lib:/var/lib/onlyoffice'
       - './onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data'
       - './onlyoffice/DocumentServer/logs:/var/log/onlyoffice'
    restart: always
    ports:
       - '2280:80'
    tty: true
    stdin_open: falus
    networks:
       - nextcloud  
networks:
   nextcloud:
    driver: 'bridge'
volumes:
  app_data:
  mysql_data:
